var sys = require('sys');

desc('This is the default task.');
task('default', [], function () {
  console.log('Running the default task.');
  console.log(sys.inspect(arguments));
});

desc('This is the asdf task. It depends on both qwer and the default');
task('asdf', ['qwer', 'default'], function () {
  console.log('Running the asdf task.');
  console.log(sys.inspect(arguments));
});

desc('This is the qwer task. It depends on zxcv, uiop, and the default');
task('qwer', ['zxcv', 'uiop', 'default'], function () {
  console.log('Running the qwer task.');
  console.log(sys.inspect(arguments));
});

desc('This is the zxcv task. It depends on the default');
task('zxcv', ['default'], function () {
  console.log('Running the zxcv task.');
  console.log(sys.inspect(arguments));
});

desc('This is the uiop task. It depends on the default');
task('uiop', ['default'], function () {
  console.log('Running the uiop task.');
  console.log(sys.inspect(arguments));
});

namespace('foo', function () {
  desc('This the foo:bar task');
  task('bar', ['default', 'foo:qux', 'foo:baz'], function () {
    console.log('doing foo:bar task');
    console.log(sys.inspect(arguments));
  });

  desc('This the foo:baz task');
  task('baz', [], function () {
    console.log('doing foo:baz task');
    console.log(sys.inspect(arguments));
  });

  desc('This the foo:qux task');
  task('qux', [], function () {
    console.log('starting async foo:qux task');
    console.log(sys.inspect(arguments));
    setTimeout(function () {
      console.log('completing async foo:qux task');
      complete();
    }, 0); 
  }, true);

});
